### ISSUE TITLE
Problems on compiling Chinese book, likely caused by fonts.

### ISSUE THREAD

**Issue by qbxdp** [RyanKruse/Andrea#2]
So I was trying to compile Chinese books into the Candle, but after compiled into blocks they all went into error code. I managed to make a Chinese font in Unity but I'm not sure which exact font I should replace in the prefab.
![image](https://user-images.githubusercontent.com/23739953/168270221-bb4e4cbd-d5d0-4f88-b494-cc5c3f52651d.png)

**Comment by RyanKruse** [comment]
Examining the issue now. I'll try it with Chinese font and see if it works or breaks.

**Comment by RyanKruse** [comment]
Andrea works with Chinese fonts now. I am in the process of publishing Andrea by this month. Full support for nearly language will come with the release. As of right now I'm not updating Candle v2.0, which is the current prefab available for download.

**Comment by qbxdp** [comment]
This is awesome! Thank you very much!
